# Generated by Django 4.1.2 on 2022-10-17 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
