# Generated by Django 4.1.2 on 2022-10-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_disabled_users_email_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='disabled',
            field=models.BooleanField(default=True),
        ),
    ]
