# Generated by Django 4.1.2 on 2022-10-22 21:05

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
